export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

//load
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SORT_PRODUCT = "SORT_PRODUCT"

//Single product
export const GET_SINGLE_PRODUCTS_BEGIN = "GET_SINGLE_PRODUCTS_BEGIN";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCTS_ERROR = "GET_SINGLE_PRODUCTS_ERROR";


export const UPDATE_SORT = "UPDATE_SORT";
